### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by drwelby** [Double-Y-EY-Challenge-2024/EY-challenge-2024#1]
Hi, I'm the tech lead for the Maxar Open Data Program that provided the source imagery for this challenge. We'd like to add the challenge and some solutions to the ODP web site.

- Is it OK to link to this repo?
- If so, could you add a license file so it's clear what people can and can't do with your work?

Thanks,

Marc

**Comment by yjwong1999** [comment]
Hi Marc,

Thank you for reaching out, and we're pleased to hear that you'd like to link our repository on the Maxar Open Data Program website. We're glad our work can contribute to your challenge and solutions! We will add an MIT license to this repository.

Thanks again for your interest and support. Please let us know when you have linked our repo to the ODP web site!
